# Generated by Django 6.0.7 on 2026-07-28 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('service_type', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Youth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('location', models.CharField(max_length=255)),
                ('primary_need', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_needed', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Emergency', 'Emergency')], default='Medium', max_length=10)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Accepted', 'Accepted'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Submitted', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiving_organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to='api.organisation')),
                ('referring_organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to='api.organisation')),
                ('youth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='api.youth')),
            ],
        ),
    ]
