# Generated by Django 6.0.7 on 2026-08-11 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='availability',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organisation',
            name='category',
            field=models.CharField(choices=[('Health', 'Health'), ('Mental Health', 'Mental Health'), ('Shelter', 'Shelter'), ('Legal', 'Legal'), ('GBV', 'GBV'), ('Education', 'Education'), ('Vocational Training', 'Vocational Training'), ('Psychosocial Support', 'Psychosocial Support'), ('Livelihood', 'Livelihood')], default='Shelter', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisation',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organisation',
            name='operating_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='target_age_group',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='organisation',
            name='target_gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='youth',
            name='immediate_needs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='youth',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Emergency', 'Emergency')], default='Medium', max_length=10),
        ),
        migrations.AddField(
            model_name='youth',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='referral',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Received', 'Received'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Information Requested', 'Information Requested'), ('Appointment Scheduled', 'Appointment Scheduled'), ('Client Arrived', 'Client Arrived'), ('Service In Progress', 'Service In Progress'), ('Service Completed', 'Service Completed'), ('Closed', 'Closed')], default='Submitted', max_length=30),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('is_urgent', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.referral')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_notes', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.organisation')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_log', to='api.referral')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
